package com.nexos.ai.domain.model

/**
 * Universal AI response shape returned by every [com.nexos.ai.ai.AIProvider].
 *
 * Architecture Law 2: every operation emits a clear state. AI calls never throw
 * out of the provider boundary — they always return a populated AIResponse.
 */
data class AIResponse(
    val text: String,
    val isSuccess: Boolean,
    val error: String? = null,
    val provider: String = "",
    val tokensUsed: Int = 0
) {
    companion object {
        fun failure(error: String, provider: String = ""): AIResponse =
            AIResponse(text = "", isSuccess = false, error = error, provider = provider)
    }
}

/**
 * Result of parsing structured AI output. Generated by [com.nexos.ai.ai.NoteAIHelper.parse].
 * Null fields fall back to safe defaults in the orchestrator.
 */
data class ParsedNote(
    val title: String,
    val bullets: List<String>,
    val summary: String
) {
    fun toMarkdownContent(): String = buildString {
        if (bullets.isNotEmpty()) {
            bullets.forEach { line ->
                appendLine("• ${line.trim()}")
            }
        }
        if (summary.isNotBlank()) {
            if (bullets.isNotEmpty()) appendLine()
            appendLine(summary.trim())
        }
    }.trim()
}
